import React from 'react';
import { 
  FlaskConical, 
  TrendingUp, 
  CheckCircle2, 
  ArrowRight, 
  Layers, 
  ShieldCheck, 
  RefreshCw,
  BarChart2,
  Info
} from 'lucide-react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer, 
  CartesianGrid, 
  Legend 
} from 'recharts';

export default function ExperimentResultPanel({ experiment, onReRunExperiment, isRunning }) {
  if (!experiment) return null;

  const control = experiment.control || {};
  const treatment = experiment.treatment || {};

  const ctrlVerified = control.verified_gmv || 120000;
  const treatVerified = treatment.verified_gmv || 270000;
  const incGMV = experiment.incremental_gmv || (treatVerified - ctrlVerified);
  const incPct = experiment.incremental_gmv_pct || 125.0;

  const chartData = [
    {
      name: 'Control (Thin Catalog)',
      'Verified AI GMV': control.verified_gmv || 120000,
      'Ambiguous GMV': control.ambiguous_gmv || 85000,
      'Rejected Spoof GMV': control.rejected_gmv || 28000,
    },
    {
      name: 'Treatment (Approved Fix)',
      'Verified AI GMV': treatment.verified_gmv || 270000,
      'Ambiguous GMV': treatment.ambiguous_gmv || 143000,
      'Rejected Spoof GMV': treatment.rejected_gmv || 29000,
    },
  ];

  return (
    <div className="space-y-6">
      
      {/* Page Header with Controlled Simulation Badge */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-surface-card border border-surface-border p-6 rounded-2xl">
        <div>
          <div className="flex items-center space-x-2 text-xs font-semibold text-brand-blue uppercase tracking-wider">
            <span>05 EXPERIMENT & 06 VERIFY</span>
            <span>•</span>
            <span>A/B Controlled Traffic Simulation</span>
          </div>
          <h1 className="text-2xl font-extrabold text-white mt-1">
            Treatment vs. Control Experiment Results
          </h1>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            Simulated over identical underlying consumer traffic volume. Measures true incremental revenue generated by the approved catalog fix.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <span className="px-3 py-1 rounded-lg text-xs font-semibold bg-brand-500/10 text-brand-blue border border-brand-500/30">
            Controlled simulation result
          </span>
          <button
            onClick={onReRunExperiment}
            disabled={isRunning}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-surface-dark border border-surface-border hover:border-slate-600 text-xs font-semibold text-slate-200 transition-colors"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRunning ? 'animate-spin text-brand-blue' : ''}`} />
            <span>{isRunning ? 'Simulating...' : 'Re-run Simulation'}</span>
          </button>
        </div>
      </div>

      {/* Hero Incremental GMV Result Box */}
      <div className="rounded-2xl bg-gradient-to-r from-[#0c203b] via-surface-card to-[#0d172a] border-2 border-emerald-500/50 p-6 shadow-2xl glow-emerald">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          
          <div className="space-y-2">
            <div className="text-xs font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-1.5">
              <TrendingUp className="w-4 h-4" />
              Verified Incremental AI GMV Measured
            </div>
            <div className="flex items-baseline space-x-3">
              <span className="text-4xl sm:text-5xl font-black text-white font-mono">
                +₹{(incGMV / 100000).toFixed(2)}L
              </span>
              <span className="text-lg sm:text-xl font-extrabold text-emerald-400 font-mono">
                (+{incPct}% Lift)
              </span>
            </div>
            <p className="text-xs text-slate-300 max-w-xl leading-relaxed">
              Strictly calculated by the deterministic backend: <code className="text-slate-200 font-mono bg-surface-dark px-1.5 py-0.5 rounded">Treatment Verified GMV (₹{(treatVerified/100000).toFixed(2)}L) - Control Verified GMV (₹{(ctrlVerified/100000).toFixed(2)}L)</code>.
            </p>
          </div>

          {/* Quick Stat Badges */}
          <div className="grid grid-cols-2 gap-3 min-w-[260px]">
            <div className="bg-surface-dark/80 p-3 rounded-xl border border-surface-border">
              <div className="text-[10px] text-slate-400 uppercase">AI Win Share Gain</div>
              <div className="text-lg font-bold text-brand-blue font-mono mt-0.5">
                +{experiment.visibility_gain_pts ?? 9.6} pts
              </div>
              <div className="text-[10px] text-slate-400">8.2% → 17.8%</div>
            </div>
            <div className="bg-surface-dark/80 p-3 rounded-xl border border-surface-border">
              <div className="text-[10px] text-slate-400 uppercase">Incremental Orders</div>
              <div className="text-lg font-bold text-emerald-400 font-mono mt-0.5">
                +{experiment.incremental_conversions ?? 32}
              </div>
              <div className="text-[10px] text-slate-400">Razorpay Orders</div>
            </div>
          </div>

        </div>
      </div>

      {/* Side-by-Side Arm Metrics Comparison Table */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Control Arm Card */}
        <div className="bg-surface-card border border-surface-border rounded-2xl p-6 shadow-md">
          <div className="flex items-center justify-between pb-3 border-b border-surface-border">
            <div className="flex items-center space-x-2">
              <div className="w-3 h-3 rounded-full bg-slate-500" />
              <h3 className="text-sm font-bold text-white">CONTROL ARM (Original Thin Catalog)</h3>
            </div>
            <span className="text-xs font-mono text-slate-400 bg-surface-dark px-2 py-0.5 rounded border border-surface-border">
              Seed #42
            </span>
          </div>

          <div className="mt-4 space-y-3 font-mono text-xs">
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">AI Recommendation Share:</span>
              <span className="text-white font-bold">{control.ai_recommendation_share_pct || 8.2}%</span>
            </div>
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">Simulated AI Sessions:</span>
              <span className="text-white font-bold">{control.ai_sessions || 65}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">Converted Orders:</span>
              <span className="text-white font-bold">{control.conversions || 24}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">Verified AI GMV:</span>
              <span className="text-slate-200 font-bold text-sm">₹{(ctrlVerified / 100000).toFixed(2)}L</span>
            </div>
            <div className="flex justify-between py-1 text-slate-500 text-[11px]">
              <span>Excluded Ambiguous GMV:</span>
              <span>₹{((control.ambiguous_gmv || 85000) / 1000).toFixed(0)}k</span>
            </div>
          </div>
        </div>

        {/* Treatment Arm Card */}
        <div className="bg-surface-card border-2 border-brand-500/50 rounded-2xl p-6 shadow-md glow-blue">
          <div className="flex items-center justify-between pb-3 border-b border-surface-border">
            <div className="flex items-center space-x-2">
              <div className="w-3 h-3 rounded-full bg-emerald-400 animate-pulse" />
              <h3 className="text-sm font-bold text-white">TREATMENT ARM (Approved Catalyst Fix)</h3>
            </div>
            <span className="text-xs font-mono text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/30">
              Active Treatment
            </span>
          </div>

          <div className="mt-4 space-y-3 font-mono text-xs">
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">AI Recommendation Share:</span>
              <span className="text-emerald-400 font-bold text-sm">{treatment.ai_recommendation_share_pct || 17.8}%</span>
            </div>
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">Simulated AI Sessions:</span>
              <span className="text-emerald-400 font-bold">{treatment.ai_sessions || 142}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">Converted Orders:</span>
              <span className="text-emerald-400 font-bold">{treatment.conversions || 56}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-surface-border/50">
              <span className="text-slate-400">Verified AI GMV:</span>
              <span className="text-emerald-400 font-bold text-sm">₹{(treatVerified / 100000).toFixed(2)}L</span>
            </div>
            <div className="flex justify-between py-1 text-slate-500 text-[11px]">
              <span>Excluded Ambiguous GMV:</span>
              <span>₹{((treatment.ambiguous_gmv || 143000) / 1000).toFixed(0)}k</span>
            </div>
          </div>
        </div>

      </div>

      {/* Recharts Bar Chart Breakdown */}
      <div className="bg-surface-card border border-surface-border rounded-2xl p-6 shadow-md">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center space-x-2">
            <BarChart2 className="w-4 h-4 text-brand-blue" />
            <span>Revenue Classification Comparison (Control vs. Treatment)</span>
          </h3>
          <span className="text-[11px] font-mono text-slate-500">Values in ₹ INR</span>
        </div>

        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData} margin={{ top: 10, right: 30, left: 20, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1f2a3f" />
              <XAxis dataKey="name" stroke="#94a3b8" fontSize={11} />
              <YAxis stroke="#94a3b8" fontSize={11} tickFormatter={(v) => `₹${(v/1000).toFixed(0)}k`} />
              <Tooltip 
                contentStyle={{ backgroundColor: '#0d1527', borderColor: '#2e3d5b', borderRadius: '8px', fontSize: '12px' }}
                formatter={(value) => [`₹${value.toLocaleString()}`, '']}
              />
              <Legend wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
              <Bar dataKey="Verified AI GMV" fill="#10b981" radius={[4, 4, 0, 0]} />
              <Bar dataKey="Ambiguous GMV" fill="#3b82f6" radius={[4, 4, 0, 0]} />
              <Bar dataKey="Rejected Spoof GMV" fill="#f43f5e" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

    </div>
  );
}
