import React, { useState } from 'react';
import { 
  FileCode, 
  Copy, 
  Check, 
  Download, 
  Globe, 
  Webhook, 
  ShieldCheck, 
  Sparkles, 
  ArrowRight, 
  Code2, 
  CheckCircle2,
  ExternalLink,
  CheckCircle
} from 'lucide-react';

export default function StorePatchExportPanel({ activeDiff, storeUrl = 'https://apex-outdoor.vercel.app' }) {
  const [copied, setCopied] = useState(false);
  const [activeFormat, setActiveFormat] = useState('jsonld');

  const jsonLdCode = activeDiff?.fields?.find(f => f.field_name === 'structured_schema')?.proposed_value || JSON.stringify({
    "@context": "https://schema.org/",
    "@type": "Product",
    "name": "Apex Ridge Waterproof Trekking Boots",
    "image": "https://apex-outdoor.vercel.app/assets/boots-main.jpg",
    "description": "Premium waterproof monsoon trekking boots featuring IPX7 membrane (15,000mm), 420g lightweight frame, and Vibram MegaGrip sole with 5mm lugs.",
    "brand": { "@type": "Brand", "name": "Apex Ridge" },
    "offers": {
      "@type": "Offer",
      "priceCurrency": "INR",
      "price": 3499,
      "availability": "https://schema.org/InStock"
    },
    "additionalProperty": [
      { "@type": "PropertyValue", "name": "waterproof_rating", "value": "IPX7 (15,000mm)" },
      { "@type": "PropertyValue", "name": "weight", "value": "420g" },
      { "@type": "PropertyValue", "name": "outsole", "value": "Vibram MegaGrip" },
      { "@type": "PropertyValue", "name": "traction", "value": "5mm multi-directional lugs" }
    ]
  }, null, 2);

  const htmlPatch = `<!-- CATALYST AI-COMMERCE ENHANCEMENT PATCH -->
<!-- Generated by Catalyst Revenue Agent • Source: merchant_catalog.json -->
<div class="catalyst-enhanced-product" data-catalyst-sku="merch-boot-01">
  <div class="technical-specifications-grid">
    <div class="spec-item"><span class="spec-label">Waterproof Rating:</span> <span class="spec-value">IPX7 (15,000mm)</span></div>
    <div class="spec-item"><span class="spec-label">Weight:</span> <span class="spec-value">420g per boot</span></div>
    <div class="spec-item"><span class="spec-label">Outsole Type:</span> <span class="spec-value">Vibram MegaGrip 5mm Lugs</span></div>
    <div class="spec-item"><span class="spec-label">Upper Material:</span> <span class="spec-value">Ripstop Cordura + Suede</span></div>
  </div>

  <!-- Schema.org Machine-Readable Product Structured Data -->
  <script type="application/ld+json">
${jsonLdCode}
  </script>
</div>`;

  const webhookPayload = JSON.stringify({
    event: "catalyst.patch.published",
    store_id: "store_apex_01",
    store_url: storeUrl,
    product_id: "merch-boot-01",
    status: activeDiff?.status || "approved",
    unsupported_claims_count: 0,
    attributes_added: [
      { key: "waterproof_rating", val: "IPX7 (15,000mm)" },
      { key: "weight", val: "420g" },
      { key: "outsole", val: "Vibram MegaGrip" },
      { key: "traction", val: "5mm multi-directional lugs" }
    ],
    timestamp: new Date().toISOString()
  }, null, 2);

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (filename, content) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const cleanDomain = storeUrl.replace(/^https?:\/\//, '').replace(/\/$/, '');

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-[#121624]/95 border border-slate-700/80 p-6 rounded-3xl shadow-xl">
        <div className="space-y-1">
          <div className="flex items-center space-x-2 text-xs font-mono font-semibold text-blue-400 uppercase tracking-wider">
            <Code2 className="w-4 h-4" />
            <span>Storefront Deployment Payloads</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-display font-bold text-white">
            Publish & Export Verified Fix Patch
          </h2>
          <p className="text-xs text-slate-300 font-sans max-w-2xl leading-relaxed">
            Deploy the verified fix to your live store. Catalyst automatically patches the live connected storefront upon approval and provides machine-readable export artifacts for Shopify, WooCommerce, Next.js Commerce, or custom CMS APIs.
          </p>
        </div>

        <div className="flex items-center space-x-2 flex-shrink-0">
          <span className="text-xs font-mono text-emerald-300 bg-emerald-950/60 px-3 py-1.5 rounded-xl border border-emerald-800/60 flex items-center gap-1.5 font-bold">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
            <span>0 Hallucinated Claims</span>
          </span>
        </div>
      </div>

      {/* Option A & B Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-stretch">
        
        {/* Left Column: Integration Pathways (1 Col) */}
        <div className="space-y-4 lg:col-span-1 flex flex-col justify-between">
          
          {/* Pathway A: Connected Storefront */}
          <div className="bg-[#121624]/95 border border-slate-700/80 rounded-3xl p-5 space-y-3 shadow-lg">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                <Globe className="w-4 h-4 text-blue-400" />
                <span>Connected Storefront</span>
              </span>
              <span className="text-[10px] font-mono text-emerald-300 bg-emerald-950 px-2 py-0.5 rounded-md border border-emerald-800 font-bold">
                Active
              </span>
            </div>

            <p className="text-xs text-slate-300 font-sans leading-relaxed">
              Direct storefront integration with <strong>Apex Ridge Outdoors</strong>. The approved patch is synchronized to your live product page.
            </p>

            <div className="p-3 bg-[#090c14] rounded-2xl border border-slate-800 text-[11px] font-mono space-y-1.5 text-slate-400">
              <div className="flex items-center justify-between">
                <span>Store:</span>
                <a 
                  href={storeUrl} 
                  target="_blank" 
                  rel="noreferrer"
                  className="text-emerald-400 hover:underline flex items-center gap-1 font-bold"
                >
                  <span>{cleanDomain}</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>
              <div className="flex items-center justify-between">
                <span>SKU:</span>
                <strong className="text-blue-300">merch-boot-01</strong>
              </div>
              <div className="flex items-center justify-between">
                <span>Status:</span>
                <strong className="text-emerald-400 font-semibold">
                  {activeDiff?.status === 'approved' || activeDiff?.status === 'applied' ? 'Published & Active' : 'Awaiting Approval'}
                </strong>
              </div>
            </div>
          </div>

          {/* Pathway B: Webhook / Headless CMS */}
          <div className="bg-[#121624]/95 border border-slate-700/80 rounded-3xl p-5 space-y-3 shadow-lg">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                <Webhook className="w-4 h-4 text-indigo-400" />
                <span>Headless CMS Webhook</span>
              </span>
              <span className="text-[10px] font-mono text-slate-400 bg-slate-900 px-2 py-0.5 rounded-md border border-slate-800">
                Ready
              </span>
            </div>

            <p className="text-xs text-slate-300 font-sans leading-relaxed">
              Automatically push verified structured fixes to headless commerce APIs (Next.js Commerce, Strapi, Sanity, Contentful, Custom API).
            </p>

            <div className="p-3 bg-[#090c14] rounded-2xl border border-slate-800 text-[10px] font-mono text-slate-400 truncate">
              POST https://{cleanDomain}/api/webhooks/catalyst
            </div>
          </div>

          {/* Trust Guarantee Box */}
          <div className="bg-emerald-950/30 border border-emerald-800/60 rounded-3xl p-4 space-y-2">
            <div className="flex items-center space-x-2 text-xs font-mono font-bold text-emerald-300">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>Strict Fact Integrity Guarantee</span>
            </div>
            <p className="text-[11px] text-slate-300 leading-relaxed font-sans">
              Every single attribute, measurement, and FAQ in this patch is deterministically verified against your catalog source data.
            </p>
          </div>

        </div>

        {/* Right Column: Code Patch Exporter (2 Cols) */}
        <div className="lg:col-span-2 bg-[#090c14] border border-slate-700/80 rounded-3xl p-6 flex flex-col space-y-4 shadow-xl">
          
          {/* Format Tabs & Action Buttons */}
          <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-slate-800 font-mono">
            <div className="flex items-center space-x-1.5 bg-slate-900 p-1 rounded-2xl border border-slate-800">
              <button
                onClick={() => setActiveFormat('jsonld')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                  activeFormat === 'jsonld'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Schema.org JSON-LD
              </button>
              <button
                onClick={() => setActiveFormat('html')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                  activeFormat === 'html'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                product-page.html
              </button>
              <button
                onClick={() => setActiveFormat('webhook')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                  activeFormat === 'webhook'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Webhook Payload
              </button>
            </div>

            <div className="flex items-center space-x-2">
              <button
                onClick={() => handleCopy(activeFormat === 'jsonld' ? jsonLdCode : activeFormat === 'html' ? htmlPatch : webhookPayload)}
                className="px-3.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 border border-slate-700 text-xs text-slate-300 hover:text-white transition-colors flex items-center space-x-1.5 cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied!' : 'Copy Code'}</span>
              </button>

              <button
                onClick={() => handleDownload(
                  activeFormat === 'jsonld' ? 'product-schema.json' : activeFormat === 'html' ? 'product-page-patch.html' : 'catalyst-patch.json',
                  activeFormat === 'jsonld' ? jsonLdCode : activeFormat === 'html' ? htmlPatch : webhookPayload
                )}
                className="px-3.5 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold transition-all flex items-center space-x-1.5 cursor-pointer shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download</span>
              </button>
            </div>
          </div>

          {/* Code Viewer */}
          <div className="flex-1 bg-[#05070d] p-5 rounded-2xl border border-slate-800/80 overflow-x-auto">
            <pre className="text-xs font-mono text-emerald-300 leading-relaxed">
              <code>
                {activeFormat === 'jsonld' && jsonLdCode}
                {activeFormat === 'html' && htmlPatch}
                {activeFormat === 'webhook' && webhookPayload}
              </code>
            </pre>
          </div>

        </div>

      </div>

    </div>
  );
}

